### ISSUE TITLE
Criar um método de teste para validar o pagamento dos Empregados

### ISSUE THREAD

**Issue by gabrielNNunes** [gabrielNNunes/AtividadeA8_EngSoftII#8]
O valor do pagamento dos funcionários deve ser maior ou igual ao valor atual do salário mínimo, que corresponde a R$ 1.100,00.
          Isso significa que valores menores precisam ser arredondados para R$ 1.100,00. (método realizarPagamento). 
          Criar cenários de teste para validar entradas:
               >Com valores abaixo do salário mínimo;
               >Acima do salário mínimo;
               >e exatamente igual ao salário Mínimo. Considere a classe Empregado.

**Comment by ThomasEdsonNunes** [comment]
close #8
